config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :pets, only: [:index, :show, :new, :create, :edit, :update]
  resources :shelters
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/mypage' => 'users#show'
  get '/home' => 'users#show'
  
  get '/apply' => 'pets#application'

  resources :shelters, only: [:show] do
    resources :pets, only: [:show, :index, :new, :edit]
  end

  patch 'pets/:id', to: 'pets#update'
  get '/pets/:id/apply', to: 'pets#edit'
  patch '/pets/:id/apply', to: 'pets#update'

  
  get 'signout', to: 'sessions#destroy', as: "signout"
  get 'auth/failure', to: redirect('/')

  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'

  



  root 'users#welcome'

end

app/models/shelter.rb
class Shelter < ActiveRecord::Base 
    has_many :pets
    has_many :shelter_users
    has_many :users, through: :shelter_users

    validates :name, uniqueness: true
    
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
    before_action :require_login
    def new
        @shelter = Shelter.new
       
    end

    def create
        @shelter = Shelter.create(shelter_params)
    
        if @shelter.valid?
            @shelter.user_id = current_user.id
            @shelter.save
            redirect_to shelter_path(@shelter)
        else
            flash[:alert] = "There was an error. Please try again."
            render :new
        end
    end

    def show
        
        @shelter = Shelter.find_by(id: params[:id])
    end

    def edit
        @shelter = Shelter.find_by(id: params[:id])
    end

    def index
        @shelters = Shelter.all
    end

    def update
        @shelter = Shelter.find(params[:id])
        @shelter.update(shelter_params)
        redirect_to shelter_path(@shelter)
    end


    private
    
    def shelter_params
        params.require(:shelter).permit(:name, :address, :email)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end
end

app/views/shelters/_form.html.erb
<% if shelter.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(shelter.errors.count, "error") %>
      prohibited this shelter from being saved:
    </h4>
 
    <ul>
    <% shelter.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(shelter) do |f| %>
  <%=f.label :name%> 
  <%=f.text_field :name %><br>
  <%=f.label :address %>
  <%=f.text_field :address %>
  <br>
  <%=f.label :email %>
  <%=f.text_field :email %><br>
  
  <%= f.submit%>
<% end %>

app/views/shelters/edit.html.erb
<% if @shelter.users.include?(current_user) %>
<%= form_tag shelter_path(@shelter), method: "put" do %>
 <%= render partial: 'form', locals: {shelter: @shelter}, post: Shelter.new %>
<% end %>
<%else%>
Sorry, you do not have access to this page. Please <%=link_to 'click', pets_path%> to view all available pets. 
<%end%>

app/views/shelters/index.html.erb
<h1>All Shelters</h1> 
<%@shelters.map do |s|%><br>
Name: <%=link_to s.name, shelter_path(s) %><br>
Contact: <%=s.email%><br>
<%end%>

app/views/shelters/new.html.erb
<% if current_user.shelter_admin == true %>

<%= render partial: 'form', locals: {shelter: @shelter}, post: Shelter.new %>

<%else%>
Sorry, you do not have access to this page. Please <%=link_to 'click', pets_path%> to view all available pets. 
<%end%>

app/views/shelters/show.html.erb
Shelter Name: <%=@shelter.name%><br>
Shelter Address: <%=@shelter.address%><br>
Contact Email: <%=@shelter.email%><br>
<%=link_to 'Browse Available Pets', shelter_pets_path(@shelter.id)%>
<br>

<% if @shelter.users.include?(current_user) %>
<%=link_to 'Add a pet to your shelter here.', new_shelter_pet_path(@shelter) %><br>
<%=link_to 'Edit your shelter information here.', edit_shelter_path(@shelter) %>
<%end%>