config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :pets, only: [:index, :show, :new, :create, :edit, :update]
  resources :shelters
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/mypage' => 'users#show'
  get '/home' => 'users#show'
  
  get '/apply' => 'pets#application'

  resources :shelters, only: [:show] do
    resources :pets, only: [:show, :index, :new, :edit]
  end

  patch 'pets/:id', to: 'pets#update'
  get '/pets/:id/apply', to: 'pets#edit'
  patch '/pets/:id/apply', to: 'pets#update'

  
  get 'signout', to: 'sessions#destroy', as: "signout"
  get 'auth/failure', to: redirect('/')

  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'

  



  root 'users#welcome'

end

app/models/pet.rb
class Pet < ActiveRecord::Base 
    belongs_to :shelter
    belongs_to :user
    validates :name, format: { without: /[0-9]/, message: "does not allow numbers" }
    validates :pet_type, format: { without: /[0-9]/, message: "does not allow numbers" }
    validates :breed, format: { without: /[0-9]/, message: "does not allow numbers" }
    validates :gender, format: { without: /[0-9]/, message: "does not allow numbers" }


    def self.boys
        where(gender: "Boy")
    end
    
    def self.girls
        where(gender: "Girl")
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
    before_action :require_login

    def new
        if params[:shelter_id]
            @pet = Pet.new(shelter_id: params[:shelter_id])
        else
            @pet = Pet.new
        end
    end

    def index
        if params[:shelter_id]
            @pets = Shelter.find_by(id: params[:shelter_id]).pets
        elsif !params[:gender].blank?
            if params[:gender] == "Boy"
                @pets = Pet.boys
            else
                @pets = Pet.girls
            end
        else
            @pets = Pet.all
        end
    end

    def create
        @pet = Pet.create(pet_params)
        @pet.user_id = current_user.id
        @pet.shelter_id = current_user.shelters.last.id
        if @pet.valid?
            @pet.save
            redirect_to pet_path(@pet)
        else
            render :new
        end
    end

    def show
        @pet = Pet.find_by(id: params[:id])
    end

    def edit
        @pet = Pet.find_by(id: params[:id])
    end


    def update
        @pet = Pet.find_by(id: params[:id])
   
        @pet.update(pet_params)
        if @pet.adopted == true
            @pet.user_id = current_user.id
            @pet.save
        end
        redirect_to pet_path(@pet)
    end

    def application
        @pet = Pet.find_by(params[:id])

        @pet.update(pet_params)
        @pet.user_id = current_user.id
        @pet.save
        redirect_to pet_path(@pet)
    end

    private
    
    def pet_params
        params.require(:pet).permit(:name, :pet_type, :gender, :neutered, :breed, :description, :adopted, :shelter_id, :city_id)
    end

    def require_login
        return head(:forbidden) unless session.include? :user_id
    end


end

app/views/pets/_adoption_form.html.erb
<%= form_for(pet) do |f| %>
  Name: <%=pet.name%><br>
  Pet Type: (dog, cat, etc.) <%=pet.pet_type%><br>
  Breed: <%=pet.breed %><br>
  Boy or Girl?: <%=pet.gender %><br>
  Neutered?: <%= pet.neutered == true ? "Yes." : "No."%><br>
  Description: <%=pet.description%><br>
  Check the box if you'd like to adopt <%=pet.name%>:  
  Yes, I do!
  <%= f.check_box :adopted, {}, "true", "false" %><br>
  
  <%= f.submit %>
<% end %>

app/views/pets/_form.html.erb
<% if pet.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(pet.errors.count, "error") %>
      prohibited this pet from being saved:
    </h4>
 
    <ul>
    <% pet.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(pet) do |f| %>
  <%= f.hidden_field :shelter_id %>
  Name: <%=f.text_field :name %><br>
  Pet Type: (dog, cat, etc.) <%=f.text_field :pet_type %><br>
  Breed: <%=f.text_field :breed %><br>
  Boy or Girl?: <%=f.text_field :gender %><br>
  Neutered?: <%=f.check_box :neutered, {}, "true", "false" %><br>
  Description: <%=f.text_area :description%><br>
  Adopted?: <%= f.check_box :adopted, {}, "true", "false" %><br>
  
  <%= f.submit %>
<% end %>

app/views/pets/_pet_profile.html.erb
Name: <%=pet.name%><br>
Pet Type: <%=pet.pet_type%><br>
Breed: <%=pet.breed%><br>
More about me: <%=pet.description%><br>
Boy or Girl?: <%= pet.gender %><br>
Neutered?: 
<%if pet.neutered == true %>
Yes.
<%else%>
No, I'm not.
<%end%><br>
My Shelter: <%=link_to pet.shelter.name, shelter_path(pet.shelter) %><br>

Available?: <% if pet.adopted == false %>
<%= "Yes, I need a new home!" %>
<% else %>
<%= "I've found a home."%>
<%end%>
<br>
<br>
<% if logged_in? && current_user.shelter_admin == false && current_user.pets.include?(pet) %>
Click to edit <%= link_to pet.name, edit_pet_path(pet) if pet.user %>'s page.
<%elsif logged_in? && current_user.shelters.include?(pet.shelter)%>
Click to edit <%= link_to pet.name, edit_shelter_pet_path(pet.shelter, pet) if pet.shelter %>'s page.
<%else%>

<%end%>

app/views/pets/application.html.erb
<% if @pet.user =/= current_user %>
<%= form_tag pet_path(@pet), method: "put" do %>
 <%= render partial: 'form', locals: {pet: @pet}, post: Pet.new %>
<% end %>


Adopter Name: <%=current_user.name%>
Contact: <%=current_user.email%>

app/views/pets/edit.html.erb
<%= form_tag pet_path(@pet), method: "put" do %>
    <% if @pet.user == current_user || current_user.shelters.include?(@pet.shelter)%>
 <%= render partial: 'form', locals: {pet: @pet}, post: Pet.new %>
 <%else%>
 <%= render partial: 'adoption_form', locals: {pet: @pet}, post: Pet.new %>
 <%end%>
<% end %>

app/views/pets/index.html.erb
<h5>All Pets:</h5> 
<div>
<h5>Filter pets:</h5>
  <%= form_tag("/pets", method: "get") do %>
    <%= select_tag "gender", options_for_select(["Boy", "Girl"]), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
</div>


<div class="container">
<div class="row">
<%@pets.each do |p| %>


  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
      <h5 class="card-title"> <%=p.name%> </h5>
      <p class="card-text"><%= render partial: "pet_profile", locals: {pet: p} %></p>

      <%if p.adopted == false %>
      <a href="/pets/<%=p.id%>/apply" class="btn btn-primary">Click to Apply</a>
      <%else%>
      <%end%>
      </div>
      </div>
</div>

<%end%>
</div>
</div>

<br>
Click <%=link_to 'here', '/'%> to go to the home page.

app/views/pets/new.html.erb
<%if current_user.shelter_admin == true && current_user.shelters.include?(@pet.shelter) %>
<%= render partial: 'form', locals: {pet: @pet}, post: Pet.new %>
<%else%>
Sorry, you do not have access to this page. Please <%=link_to 'click', pets_path%> to view all available pets. 

<%end%>

app/views/pets/show.html.erb
<%= render partial: "pet_profile", locals: {pet: @pet} %>

<br>
Click <%=link_to 'here', pets_path%> to go to the pets page.
<br>
Click <%=link_to 'here', '/'%> to go to the home page.