config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :pets, only: [:index, :show, :new, :create, :edit, :update]
  resources :shelters
  resources :sessions

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/mypage' => 'users#show'
  get '/home' => 'users#show'
  
  get '/apply' => 'pets#application'

  resources :shelters, only: [:show] do
    resources :pets, only: [:show, :index, :new, :edit]
  end

  patch 'pets/:id', to: 'pets#update'
  get '/pets/:id/apply', to: 'pets#edit'
  patch '/pets/:id/apply', to: 'pets#update'

  
  get 'signout', to: 'sessions#destroy', as: "signout"
  get 'auth/failure', to: redirect('/')

  get 'auth/google_oauth2/callback', to: 'sessions#googleAuth'

  



  root 'users#welcome'

end

app/models/user.rb
class User < ActiveRecord::Base 
    has_secure_password
    validates :email, uniqueness: true
    validates :username, uniqueness: true
    validates :name, format: { without: /[0-9]/, message: "does not allow numbers" }
    has_many :pets
    has_many :shelter_users
    has_many :shelters, through: :shelter_users

    attr_accessor :shelters_attributes

    def shelters_attributes=(shelter_attributes)
        shelter_attributes.values.each do |shelter_attribute|
             shelter = Shelter.find_or_create_by(shelter_attribute)
          self.shelters << shelter
        end
      end

    def self.from_google(auth)
        refresh_token = auth.credentials.refresh_token
        if (found_user = User.find_by(email: auth.info.email))
            found_user.google_uid = auth.credentials.token
            found_user.google_refresh_token = refresh_token if refresh_token.present?
            return found_user
        else
            new_user = User.create do |u|
                u.email = auth.info.email
                u.name = auth.info.name
                u.username = auth.info.email
                u.google_uid = auth.credentials.token
                u.google_refresh_token = refresh_token if refresh_token.present?
                u.password = Sysrandom.hex(30)
            end
            return new_user
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.create(user_params)

        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            if @user.shelter_admin == true
                redirect_to new_shelter_path
            else
                redirect_to user_path(@user)
            end
        else
            render :new
        end
    end


    def show
        @user = User.find_by(id: params[:id])

        if current_user != @user 
            redirect_to '/'
        end
    end

    def edit
        @user = User.find_by(id: params[:id])
    end

    def update
        @user = current_user
        @user.update(user_params)
        redirect_to user_path(@user)
    end


    private

    def user_params
        params.require(:user).permit(:name, :username, :password, :email, :shelter_admin, :uid, :provider, :shelter_ids => [], shelters_attributes: [:name, :email, :address])
    end

end

app/views/users/_form.html.erb
<% if user.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(user.errors.count, "error") %>
      prohibited this user from being saved:
    </h4>
 
    <ul>
    <% user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(user) do |f| %>
  Name: <%=f.text_field :name %><br>

  Username: <%=f.text_field :username %><br>
  Password: <%=f.password_field :password %><br>
  Email: <%=f.text_field :email %><br>
  Check if you are representing a shelter.
  <%= f.check_box :shelter_admin, {}, "true", "false" %><br>

  If you are a shelter manager, please add your shelter's information down below: <br> 
  
  <%= f.fields_for :shelters, user.shelters.build do |shelter_fields| %>
    Name: <%= shelter_fields.text_field :name %><br>
    Email: <%= shelter_fields.text_field :email %><br>
    Address: <%= shelter_fields.text_field :address %><br>
  <% end %>
  <%= f.submit%>
<% end %>

<%= button_to 'Sign in via Google', '/auth/google_oauth2' %>

app/views/users/_if_shelter_admin.html.erb
<% current_user.shelters.map do |s| %>
    <% if s.name == ""%>
        <% %>
    <%else%>
        Manage <%= link_to s.name, shelter_path(s) %> here.<br>
    <%end%>
<%end%>

Create a new shelter <%=link_to 'here', new_shelter_path%>.

app/views/users/_user_info.html.erb
<h1>Welcome, <%=current_user.name%>.</h1>
Your registered information is down below:<br>
Username: <%=current_user.username%> <br>
Contact Email: <%=current_user.email%><br>

<% if current_user.shelter_admin == true %>
<%= render partial: "if_shelter_admin", locals: {user: user} %>
<%end%>
<br>
Click <%=link_to 'here', pets_path %> to view all pets.

app/views/users/edit.html.erb
<% if @user == current_user %>

<%= form_tag user_path(@user), method: "put" do %>
 <%= render partial: 'form', locals: {user: @user}, post: User.new %>
<% end %>

<%else%>
Sorry, you do not have access to this page. Please <%=link_to 'click', pets_path%> to view all available pets. 
<%end%>

app/views/users/new.html.erb
<%= render partial: 'form', locals: {user: @user}, post: User.new %>

app/views/users/show.html.erb
<%= render partial: "user_info", locals: {user: @user} %>

<br>
<%=link_to 'Click here to edit your profile.', edit_user_path(@user) %>

app/views/users/welcome.html.erb
Bringing shelters and adopters together since 2019<br><br>

<% if current_user == nil %>
<h5>Looking for a pet?</h5>
<h5><%=link_to 'Sign up', '/signup' %> or <%=link_to 'log in', '/login' %> to start looking at available pets or to start managing your shelter.</h5>
<br>
 
<% elsif current_user.shelter_admin == true%>
Welcome, <%=current_user.name%>.<br>
<% if current_user.shelter_admin == true %>
<%= render partial: "if_shelter_admin", locals: {user: current_user} %>
<%end%>
<br>
Click to manage your <%=link_to 'user page', user_path(current_user)%>.

<br>
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='Log Out'>
<% end %>
<%else%>
Welcome, <%=current_user.name%>. <br>
Click to manage your <%=link_to 'page', user_path(current_user)%>.
<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='Log Out'>
<% end %>

<%end%>